"use client";

import type { AdminRequest } from "@/lib/admin-client";
import type { ReviewSettingsProfile, ReviewSettingsStageType } from "@/lib/contracts";
import { Background, Controls, Handle, Position, ReactFlow, addEdge, useEdgesState, useNodesState, type Connection, type Edge, type Node, type NodeProps } from "@xyflow/react";
import { Check, CircleAlert, Copy, GitBranch, MousePointer2, PanelLeftOpen, Plus, RotateCcw, Save, Send, Star, Trash2, Webhook, X } from "lucide-react";
import { useCallback, useEffect, useState } from "react";

type Stage = { id?: number; stage_type_key: string; executor_key?: string; key: string; name: string; prompt_template: string; model_id?: number; max_output_tokens: number; retry_limit: number; timeout_seconds: number; use_llm: boolean; required: boolean; config: Record<string, unknown>; input_contract?: { key: string }; output_contract?: { key: string } };
type Transition = { id?: number; from_stage_id?: number; to_stage_id?: number; from_stage_key?: string; to_stage_key?: string; type: string; condition_key: string; priority: number };
type Trigger = { source: "webhook" | "api" | "manual"; enabled: boolean };
type Version = { id: number; version: number; status: string; profile_id?: number; stages: Stage[]; transitions: Transition[]; triggers: Trigger[] };
type Pipeline = { id: number; name: string; description: string; profile_id?: number; is_default: boolean; versions: Version[] };
type StudioNodeData = { stage: Stage; update: (patch: Partial<Stage>) => void; remove: () => void; select: () => void; editable: boolean };

const triggerLabels = { webhook: "Webhook Gitea", api: "POST API", manual: "Disparo manual" };
const conditions = ["always", "has_findings", "no_findings", "partial_result", "contract_invalid", "confidence_below_threshold"];

function StudioNode({ data }: NodeProps<Node<StudioNodeData>>) {
  const s = data.stage;
  return <article className={`studio-node ${s.executor_key === "error_log" ? "error" : ""}`} onClick={data.select}>
    <Handle type="target" position={Position.Left} className="studio-handle input" />
    <header><span><i />{s.name}</span>{data.editable && <button aria-label="Remover etapa" onClick={data.remove}><Trash2 size={13} /></button>}</header>
    <small>{s.input_contract?.key || "Entrada inicial"} <b>{"->"}</b> {s.output_contract?.key || "Terminal"}</small>
    <div className="studio-fields">
      <label>Nome<input disabled={!data.editable} value={s.name} onChange={(e) => data.update({ name: e.target.value })} /></label>
      <label>Prompt<textarea disabled={!data.editable} value={s.prompt_template} onChange={(e) => data.update({ prompt_template: e.target.value })} placeholder="Etapa determinística" /></label>
      <div><label>Modelo ID<input disabled={!data.editable} type="number" value={s.model_id ?? ""} onChange={(e) => data.update({ model_id: e.target.value ? Number(e.target.value) : undefined })} /></label><label>Tokens<input disabled={!data.editable} type="number" min="0" value={s.max_output_tokens} onChange={(e) => data.update({ max_output_tokens: Number(e.target.value) })} /></label></div>
      <div><label>Retry<input disabled={!data.editable} type="number" min="0" value={s.retry_limit} onChange={(e) => data.update({ retry_limit: Number(e.target.value) })} /></label><label>Timeout<input disabled={!data.editable} type="number" min="0" value={s.timeout_seconds} onChange={(e) => data.update({ timeout_seconds: Number(e.target.value) })} /></label></div>
    </div>
    <Handle type="source" position={Position.Right} className="studio-handle output" />
  </article>;
}
const nodeTypes = { studio: StudioNode };

export function PipelineManager({ request, profiles, catalog, onAuthError, onSaved, readOnly = false, profileID: runtimeProfileID, onPipelineName, editRequest = 0, saveRequest = 0, discardRequest = 0, onEditingChange }: { request: AdminRequest; profiles: ReviewSettingsProfile[]; catalog: ReviewSettingsStageType[]; onAuthError: () => void; onSaved: () => void; readOnly?: boolean; profileID?: number; onPipelineName?: (name: string) => void; editRequest?: number; saveRequest?: number; discardRequest?: number; onEditingChange?: (editing: boolean) => void }) {
  const [pipelines, setPipelines] = useState<Pipeline[]>([]), [pipelineID, setPipelineID] = useState<number | null>(null), [version, setVersion] = useState<Version | null>(null), [nodes, setNodes, onNodesChange] = useNodesState<Node<StudioNodeData>>([]), [edges, setEdges, onEdgesChange] = useEdgesState<Edge>([]), [name, setName] = useState(""), [description, setDescription] = useState(""), [profileID, setProfileID] = useState(""), [triggers, setTriggers] = useState<Trigger[]>(["webhook", "api", "manual"].map((source) => ({ source: source as Trigger["source"], enabled: true }))), [error, setError] = useState(""), [busy, setBusy] = useState(false), [editing, setEditing] = useState(false), [nameDialog, setNameDialog] = useState(false), [draftName, setDraftName] = useState(""), [menuOpen, setMenuOpen] = useState(false), [selectedEdge, setSelectedEdge] = useState<string | null>(null), [selectedNode, setSelectedNode] = useState<string | null>(null), [statusOpen, setStatusOpen] = useState(false);
  const current = pipelines.find((p) => p.id === pipelineID);
  const editable = editing || (!readOnly && (!version || version.status === "draft"));
  const load = useCallback(async () => { try { if (readOnly) { const item = await request<Pipeline>(`review/pipelines/select${runtimeProfileID ? `?profile_id=${runtimeProfileID}` : ""}`); const active = item.versions.find((candidate) => candidate.status === "published"); setPipelines([item]); if (active) open(active, item); return; } const items = await request<Pipeline[]>("review/pipelines"); setPipelines(items); } catch (e) { if (e instanceof Error && e.message === "AUTH") onAuthError(); else setError(e instanceof Error ? e.message : String(e)); } }, [request, onAuthError, readOnly, runtimeProfileID]);
  useEffect(() => { void load(); }, [load]);
  const stageType = (key: string) => catalog.find((item) => item.key === key);
  const buildNode = useCallback((stage: Stage, index: number): Node<StudioNodeData> => ({ id: stage.key, type: "studio", position: { x: Number(stage.config?.x ?? 100 + index * 320), y: Number(stage.config?.y ?? 140 + (index % 2) * 240) }, data: { stage, editable, select: () => { setSelectedNode(stage.key); setStatusOpen(false); }, update: (patch) => setNodes((all) => all.map((n) => n.id === stage.key ? { ...n, data: { ...n.data, stage: { ...n.data.stage, ...patch } } } : n)), remove: () => { setNodes((all) => all.filter((n) => n.id !== stage.key)); setEdges((all) => all.filter((e) => e.source !== stage.key && e.target !== stage.key)); }, } }), [editable, setNodes, setEdges]);
  function open(versionToOpen: Version, parent: Pipeline) { setPipelineID(parent.id); setVersion(versionToOpen); setName(parent.name); onPipelineName?.(parent.name); setDescription(parent.description); setProfileID(String(versionToOpen.profile_id ?? parent.profile_id ?? "")); setTriggers(versionToOpen.triggers.length ? versionToOpen.triggers : triggers); const byID = new Map(versionToOpen.stages.map((s) => [s.id, s.key])); setNodes(versionToOpen.stages.map(buildNode)); setEdges(versionToOpen.transitions.filter((t) => t.from_stage_id && t.to_stage_id).map((t, i) => ({ id: String(t.id ?? i), source: byID.get(t.from_stage_id!)!, target: byID.get(t.to_stage_id!)!, label: `${t.type}:${t.condition_key}`, data: t, animated: t.type !== "success" }))); }
  function create() { setPipelineID(null); setVersion(null); setName(""); setDescription(""); setProfileID(""); const keys = ["preparation", "verification", "formatting", "publication"]; const stages = keys.map((key, index) => newStage(key, index)); setNodes(stages.map(buildNode)); setEdges(stages.slice(0, -1).map((s, i) => ({ id: `e-${i}`, source: s.key, target: stages[i + 1].key, label: "success:always", data: { type: "success", condition_key: "always", priority: 0 } }))); }
  function discard() { if (version && current) open(version, current); else create(); setError(""); }
  function newStage(typeKey: string, index = nodes.length): Stage { const type = stageType(typeKey); const fixed: Record<string, [string, string, boolean, boolean]> = { preparation: ["preparacao", "Preparação", false, true], verification: ["verificacao", "Verificação", true, true], formatting: ["formatacao", "Formatação", true, true], publication: ["publicacao", "Publicação", false, true], error_log: ["erro", "Log de erro", false, false] }; const [key, title, llm, required] = fixed[typeKey] ?? [`${typeKey}-${Date.now()}`, type?.name ?? typeKey, true, false]; return { stage_type_key: typeKey, executor_key: type?.executor_key, key, name: title, prompt_template: "", max_output_tokens: 2000, retry_limit: 1, timeout_seconds: 900, use_llm: llm, required, config: { x: 100 + index * 70, y: 120 + index * 40 }, input_contract: type?.input_contract ? { key: type.input_contract.key } : undefined, output_contract: type?.output_contract ? { key: type.output_contract.key } : undefined }; }
  const connect = useCallback((connection: Connection) => { const source = nodes.find((n) => n.id === connection.source)?.data.stage, target = nodes.find((n) => n.id === connection.target)?.data.stage; if (!source || !target) return; if (target.executor_key !== "error_log" && source.output_contract?.key !== target.input_contract?.key) return setError("As portas só conectam contratos compatíveis."); const type = target.executor_key === "error_log" ? "failure" : "success"; setEdges((all) => addEdge({ ...connection, id: crypto.randomUUID(), label: `${type}:always`, data: { type, condition_key: "always", priority: 0 } }, all)); }, [nodes, setEdges]);
  async function save(publish = false) { const stages = nodes.map((node, index) => ({ ...node.data.stage, config: { ...node.data.stage.config, x: node.position.x, y: node.position.y }, position: index + 1 })); const transitions = edges.map((edge, priority) => ({ from_stage_key: edge.source, to_stage_key: edge.target, type: String(edge.data?.type ?? "success"), condition_key: String(edge.data?.condition_key ?? "always"), priority })); const body = { name, description, profile_id: profileID ? Number(profileID) : null, stages, transitions, triggers };
    setBusy(true); setError(""); try { if (!version) { const key = name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || `pipeline-${Date.now()}`; const created = await request<Pipeline>("review/pipelines", { method: "POST", body: JSON.stringify({ ...body, key }) }); const draft = created.versions[0]; await load(); open(draft, created); } else if (current) { await request(`review/pipelines/${current.id}/drafts/${version.id}`, { method: "PUT", body: JSON.stringify(body) }); if (publish) { await request(`review/pipelines/${current.id}/drafts/${version.id}/publish`, { method: "POST" }); setVersion(null); } await load(); } onSaved(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setBusy(false); } }
  const updateSelectedEdge = (patch: Record<string, unknown>) => setEdges((all) => all.map((edge) => edge.id === selectedEdge ? { ...edge, label: `${String(patch.type ?? edge.data?.type)}:${String(patch.condition_key ?? edge.data?.condition_key)}`, data: { ...edge.data, ...patch } } : edge));
  async function createFromCurrent() { if (!current || !version) return; setBusy(true); try { const stages = nodes.map((node, index) => ({ ...node.data.stage, config: { ...node.data.stage.config, x: node.position.x, y: node.position.y }, position: index + 1 })); const transitions = edges.map((edge, priority) => ({ from_stage_key: edge.source, to_stage_key: edge.target, type: String(edge.data?.type ?? "success"), condition_key: String(edge.data?.condition_key ?? "always"), priority })); const key = draftName.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || `pipeline-${Date.now()}`; const created = await request<Pipeline>("review/pipelines", { method: "POST", body: JSON.stringify({ key, name: draftName, description, profile_id: runtimeProfileID ?? null, stages, transitions, triggers }) }); const draft = created.versions[0]; setEditing(true); onEditingChange?.(true); await load(); open(draft, created); } catch (failure) { setError(failure instanceof Error ? failure.message : String(failure)); } finally { setBusy(false); setNameDialog(false); } }
  useEffect(() => { if (readOnly && editRequest && current && version && !editing) { setDraftName(`Cópia de ${current.name}`); setNameDialog(true); } }, [editRequest, readOnly, current, version, editing]);
  useEffect(() => { if (editing && saveRequest) void save(); }, [saveRequest]);
  useEffect(() => { if (editing && discardRequest) { setEditing(false); onEditingChange?.(false); void load(); } }, [discardRequest]);
  const selectedStage = nodes.find((node) => node.id === selectedNode)?.data.stage;
  return <section className={`pipeline-studio ${readOnly ? "runtime-studio" : ""}`}>{nameDialog && <div className="studio-dialog-backdrop"><section className="studio-name-dialog"><h2>Nome da nova pipeline</h2><p>A cópia será vinculada ao profile padrão e poderá ser selecionada manualmente depois.</p><input autoFocus value={draftName} onChange={(event) => setDraftName(event.target.value)} /><div><button className="secondary-button" onClick={() => setNameDialog(false)}>Cancelar</button><button className="primary-button" disabled={!draftName.trim() || busy} onClick={() => void createFromCurrent()}>Criar pipeline</button></div></section></div>}{!readOnly && <header className="studio-topbar"><div><span className="eyebrow">Pipeline Studio</span><h2>{name || "Novo workflow"}</h2></div><div><button className="secondary-button" disabled={busy} onClick={discard}><RotateCcw size={16} /> Descartar</button>{editable && <button className="secondary-button" disabled={busy} onClick={() => void save()}><Save size={16} /> Salvar</button>}{editable && version && <button className="primary-button" disabled={busy} onClick={() => void save(true)}><Send size={16} /> Publicar</button>}</div></header>}{error && <div className="banner error">{error}</div>}
    {menuOpen && <aside className="studio-sidebar"><button className="studio-close" onClick={() => setMenuOpen(false)} aria-label="Fechar menu"><X size={16} /></button><section><strong>Workflows</strong>{pipelines.map((p) => <button key={p.id} className={p.id === pipelineID ? "active" : ""} disabled={readOnly} onClick={() => { setPipelineID(p.id); setVersion(null); setNodes([]); setEdges([]); }}><GitBranch size={15} /> {p.name}{p.is_default && <Star size={13} />}</button>)}</section>{current && !version && <section><strong>Versões</strong>{current.versions.map((v) => <button key={v.id} disabled={readOnly} onClick={() => open(v, current)}>v{v.version} <small>{v.status}</small></button>)}{!current.is_default && <button onClick={() => void request(`review/pipelines/${current.id}/select`, { method: "POST" }).then(() => load())}><Star size={15} /> Selecionar</button>}</section>}<section><strong>Etapas</strong>{catalog.filter((t) => t.is_enabled).map((type) => <button key={type.key} disabled={!editable} draggable onDragStart={(e) => e.dataTransfer.setData("stage", type.key)} onClick={() => editable && setNodes((all) => [...all, buildNode(newStage(type.key, all.length), all.length)])}><Plus size={14} /> {type.name}</button>)}</section><section><strong>Gatilhos</strong>{triggers.map((trigger) => <label className="studio-trigger" key={trigger.source}><input disabled={!editable} type="checkbox" checked={trigger.enabled} onChange={(e) => setTriggers((all) => all.map((t) => t.source === trigger.source ? { ...t, enabled: e.target.checked } : t))} /><Webhook size={14} /> {triggerLabels[trigger.source]}</label>)}</section></aside>}
    <main className="studio-canvas" onDragOver={(e) => e.preventDefault()} onDrop={(e) => { const type = e.dataTransfer.getData("stage"); if (!type || !editable) return; const rect = e.currentTarget.getBoundingClientRect(); const stage = newStage(type); stage.config = { ...stage.config, x: e.clientX - rect.left, y: e.clientY - rect.top }; setNodes((all) => [...all, buildNode(stage, all.length)]); }}><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} onConnect={connect} onEdgeClick={(_, edge) => { setSelectedEdge(edge.id); setSelectedNode(null); setStatusOpen(false); }} fitView><Background gap={18} size={1} /><Controls /></ReactFlow><button className="studio-menu-toggle" onClick={() => setMenuOpen(true)} title="Abrir menu"><PanelLeftOpen size={17} /></button><div className="studio-hint"><MousePointer2 size={14} /> Arraste etapas, conecte portas e use o card de erro para caminhos failure/fallback.</div><button className={`studio-status ${error ? "error" : "ok"}`} onClick={() => { setStatusOpen((value) => !value); setSelectedNode(null); }} title="Status da pipeline"><CircleAlert size={16} /> {error ? "Atenção" : "Válida"}</button></main>
    {(selectedStage || statusOpen) && <aside className="studio-inspector"><button className="studio-close" onClick={() => { setSelectedNode(null); setSelectedEdge(null); setStatusOpen(false); }} aria-label="Fechar detalhes"><X size={16} /></button>{selectedStage ? <><strong>Etapa selecionada</strong><label>Nome<input disabled={!editable} value={selectedStage.name} onChange={(e) => selectedStage && setNodes((all) => all.map((node) => node.id === selectedStage.key ? { ...node, data: { ...node.data, stage: { ...node.data.stage, name: e.target.value } } } : node))} /></label><label>Contrato de entrada<input disabled value={selectedStage.input_contract?.key || "Entrada inicial"} /></label><label>Contrato de saída<input disabled value={selectedStage.output_contract?.key || "Terminal"} /></label><label>Prompt<textarea disabled={!editable} value={selectedStage.prompt_template} onChange={(e) => selectedStage && setNodes((all) => all.map((node) => node.id === selectedStage.key ? { ...node, data: { ...node.data, stage: { ...node.data.stage, prompt_template: e.target.value } } } : node))} /></label></> : <><strong>Status da pipeline</strong><div className="studio-error-note"><CircleAlert size={15} /> {error || "Pipeline carregada. Rotas failure e fallback só podem apontar para Log de erro."}</div></>}{selectedEdge && <section className="studio-edge"><strong>Conexão</strong><label>Tipo<select disabled={!editable} value={String(edges.find((e) => e.id === selectedEdge)?.data?.type ?? "success")} onChange={(e) => updateSelectedEdge({ type: e.target.value })}>{["success", "failure", "fallback", "skip"].map((v) => <option key={v}>{v}</option>)}</select></label><label>Condição<select disabled={!editable} value={String(edges.find((e) => e.id === selectedEdge)?.data?.condition_key ?? "always")} onChange={(e) => updateSelectedEdge({ condition_key: e.target.value })}>{conditions.map((v) => <option key={v}>{v}</option>)}</select></label></section>}</aside>}
  </section>;
}
