"use client";

import type { AdminRequest } from "@/lib/admin-client";
import type { ReviewSettingsProfile, ReviewSettingsStageType } from "@/lib/contracts";
import { Background, Controls, Handle, Position, ReactFlow, addEdge, useEdgesState, useNodesState, type Connection, type Edge, type Node, type NodeProps } from "@xyflow/react";
import { AlertCircle, Check, CircleAlert, Copy, GitBranch, MousePointer2, PanelLeftOpen, Plus, RotateCcw, Save, Send, Star, Trash2, Webhook, X } from "lucide-react";
import { useCallback, useEffect, useState } from "react";

type Stage = { id?: number; stage_type_key: string; executor_key?: string; key: string; name: string; position?: number; prompt_template: string; model_id?: number; max_output_tokens: number; retry_limit: number; timeout_seconds: number; use_llm: boolean; required: boolean; config: Record<string, unknown>; input_contract?: { key: string }; output_contract?: { key: string } };
type Transition = { id?: number; from_stage_id?: number; to_stage_id?: number; from_stage_key?: string; to_stage_key?: string; type: string; condition_key: string; priority: number };
type Trigger = { source: "webhook" | "api" | "manual"; enabled: boolean };
type Version = { id: number; version: number; status: string; profile_id?: number; stages: Stage[]; transitions: Transition[]; triggers: Trigger[] };
type Pipeline = { id: number; name: string; description: string; profile_id?: number; is_default: boolean; versions: Version[] };
type RuntimeEvent = { status?: string; percent?: number; message?: string; timestamp?: string };
type StudioNodeData = { stage: Stage; update: (patch: Partial<Stage>) => void; remove: () => void; select: () => void; openLogs: () => void; editable: boolean; runtime?: RuntimeEvent; active?: boolean };

const triggerLabels = { webhook: "Webhook Gitea", api: "POST API", manual: "Disparo manual" };
const conditions = ["always", "has_findings", "no_findings", "partial_result", "contract_invalid", "confidence_below_threshold"];
const defaultPositions = [{ x: 0, y: 0 }, { x: 400, y: 0 }, { x: 800, y: 0 }, { x: 1200, y: 280 }, { x: 800, y: 430 }, { x: 400, y: 430 }, { x: 0, y: 430 }];

function contractColor(key?: string) {
  if (key?.includes("findings")) return "#46c892";
  if (key?.includes("review")) return "#ab7cff";
  if (key?.includes("diff")) return "#4d91ff";
  if (key?.includes("error")) return "#e25f67";
  return "#e6a34e";
}
function portSide(stage: Stage, kind: "input" | "output") {
  const configured = stage.config?.[`${kind}_side`];
  if (configured === "left" || configured === "right") return configured;
  if (kind === "output" && ["consolidator", "verification", "formatting"].includes(stage.executor_key || "")) return "left";
  if (kind === "input" && ["verification", "formatting", "publication"].includes(stage.executor_key || "")) return "right";
  return kind === "input" ? "left" : "right";
}
function handlePosition(side: string) { return side === "left" ? Position.Left : Position.Right; }
function stagePercent(event?: RuntimeEvent) { return ["done", "concluido", "concluído", "completed"].includes(event?.status || "") ? 100 : event?.percent ?? 0; }

function StudioNode({ data }: NodeProps<Node<StudioNodeData>>) {
  const s = data.stage;
  const inputSide = portSide(s, "input");
  const outputSide = portSide(s, "output");
  return <article className={`studio-node ${s.executor_key === "error_log" ? "error" : ""}`} onClick={data.select}>
    <header><span><i />{s.name}</span>{data.editable && <button aria-label="Remover etapa" onClick={data.remove}><Trash2 size={13} /></button>}</header>
    <div className={`studio-ports ${inputSide === "right" && outputSide === "left" ? "reversed" : ""}`}><span className={`input-port ${inputSide}`}><Handle id={`input-${inputSide}`} type="target" position={handlePosition(inputSide)} className="studio-port-handle" style={{ background: contractColor(s.input_contract?.key) }} /><i style={{ background: contractColor(s.input_contract?.key) }} />{s.input_contract?.key || "Entrada inicial"}</span><span className={`output-port ${outputSide}`}>{s.output_contract?.key || "Terminal"}<i style={{ background: contractColor(s.output_contract?.key) }} /><Handle id={`output-${outputSide}`} type="source" position={handlePosition(outputSide)} className="studio-port-handle" style={{ background: contractColor(s.output_contract?.key) }} /></span></div>
    {data.editable ? <div className="studio-fields">
      <label>Nome<input disabled={!data.editable} value={s.name} onChange={(e) => data.update({ name: e.target.value })} /></label>
      <label>Prompt<textarea disabled={!data.editable} value={s.prompt_template} onChange={(e) => data.update({ prompt_template: e.target.value })} placeholder="Etapa determinística" /></label>
      <div><label>Modelo ID<input disabled={!data.editable} type="number" value={s.model_id ?? ""} onChange={(e) => data.update({ model_id: e.target.value ? Number(e.target.value) : undefined })} /></label><label>Tokens<input disabled={!data.editable} type="number" min="0" value={s.max_output_tokens} onChange={(e) => data.update({ max_output_tokens: Number(e.target.value) })} /></label></div>
      <div><label>Retry<input disabled={!data.editable} type="number" min="0" value={s.retry_limit} onChange={(e) => data.update({ retry_limit: Number(e.target.value) })} /></label><label>Timeout<input disabled={!data.editable} type="number" min="0" value={s.timeout_seconds} onChange={(e) => data.update({ timeout_seconds: Number(e.target.value) })} /></label></div>
    </div> : <div className={`studio-run-log ${data.runtime?.status || "pending"}`}><header><span>{data.active ? "Em execução" : data.runtime?.status || "Aguardando"}</span><span><strong>{stagePercent(data.runtime)}%</strong><button className="studio-log-button" onClick={(event) => { event.stopPropagation(); data.openLogs(); }} title="Abrir logs"><AlertCircle size={15} /></button></span></header><p>{data.runtime?.message || "Aguardando uma execução desta etapa."}</p><div><i style={{ width: `${stagePercent(data.runtime)}%` }} /></div></div>}
  </article>;
}
const nodeTypes = { studio: StudioNode };

function StageInspector({ stage, editable, runtime, onUpdate }: { stage: Stage; editable: boolean; runtime?: RuntimeEvent; onUpdate: (patch: Partial<Stage>) => void }) {
  if (!editable) return <><strong>Status da execução</strong><div className={`studio-inspector-status ${runtime?.status || "pending"}`}><header><span>{runtime?.status || "Aguardando"}</span><strong>{runtime?.percent ?? 0}%</strong></header><p>{runtime?.message || "Esta etapa ainda não possui eventos nesta execução."}</p><i style={{ width: `${runtime?.percent ?? 0}%` }} /></div><section className="studio-readonly-config"><strong>Configuração</strong><label>Etapa<input disabled value={stage.name} /></label><label>Entrada<input disabled value={stage.input_contract?.key || "Entrada inicial"} /></label><label>Saída<input disabled value={stage.output_contract?.key || "Terminal"} /></label><label>Modelo<input disabled value={stage.model_id ? `#${stage.model_id}` : "Modelo do profile"} /></label><label>Tokens<input disabled value={stage.max_output_tokens} /></label><label>Retry / timeout<input disabled value={`${stage.retry_limit} / ${stage.timeout_seconds}s`} /></label><label>Prompt<textarea disabled value={stage.prompt_template || "Etapa determinística"} /></label></section></>;
  return <><strong>Editar etapa</strong><label>Nome<input value={stage.name} onChange={(event) => onUpdate({ name: event.target.value })} /></label><label>Entrada<select value={portSide(stage, "input")} onChange={(event) => onUpdate({ config: { ...stage.config, input_side: event.target.value } })}><option value="left">Esquerda</option><option value="right">Direita</option></select></label><label>Saída<select value={portSide(stage, "output")} onChange={(event) => onUpdate({ config: { ...stage.config, output_side: event.target.value } })}><option value="left">Esquerda</option><option value="right">Direita</option></select></label><label>Modelo ID<input type="number" value={stage.model_id ?? ""} onChange={(event) => onUpdate({ model_id: event.target.value ? Number(event.target.value) : undefined })} /></label><label>Tokens<input type="number" min="0" value={stage.max_output_tokens} onChange={(event) => onUpdate({ max_output_tokens: Number(event.target.value) })} /></label><label>Retry<input type="number" min="0" value={stage.retry_limit} onChange={(event) => onUpdate({ retry_limit: Number(event.target.value) })} /></label><label>Timeout (s)<input type="number" min="0" value={stage.timeout_seconds} onChange={(event) => onUpdate({ timeout_seconds: Number(event.target.value) })} /></label><label>Prompt<textarea value={stage.prompt_template} onChange={(event) => onUpdate({ prompt_template: event.target.value })} /></label></>;
}

export function PipelineManager({ request, profiles, catalog, onAuthError, onSaved, readOnly = false, profileID: runtimeProfileID, onPipelineName, editRequest = 0, saveRequest = 0, discardRequest = 0, onEditingChange, runtimeEvents = {}, runtimeLogs = {}, activeStage = "", manualApproval = false, onOpenLogs, onOpenPreReview }: { request: AdminRequest; profiles: ReviewSettingsProfile[]; catalog: ReviewSettingsStageType[]; onAuthError: () => void; onSaved: () => void; readOnly?: boolean; profileID?: number; onPipelineName?: (name: string) => void; editRequest?: number; saveRequest?: number; discardRequest?: number; onEditingChange?: (editing: boolean) => void; runtimeEvents?: Record<string, RuntimeEvent>; runtimeLogs?: Record<string, RuntimeEvent[]>; activeStage?: string; manualApproval?: boolean; onOpenLogs?: (stage: string, name: string, events: RuntimeEvent[]) => void; onOpenPreReview?: () => void }) {
  const [pipelines, setPipelines] = useState<Pipeline[]>([]), [pipelineID, setPipelineID] = useState<number | null>(null), [version, setVersion] = useState<Version | null>(null), [nodes, setNodes, onNodesChange] = useNodesState<Node<StudioNodeData>>([]), [edges, setEdges, onEdgesChange] = useEdgesState<Edge>([]), [name, setName] = useState(""), [description, setDescription] = useState(""), [profileID, setProfileID] = useState(""), [triggers, setTriggers] = useState<Trigger[]>(["webhook", "api", "manual"].map((source) => ({ source: source as Trigger["source"], enabled: true }))), [error, setError] = useState(""), [busy, setBusy] = useState(false), [editing, setEditing] = useState(false), [nameDialog, setNameDialog] = useState(false), [draftName, setDraftName] = useState(""), [menuOpen, setMenuOpen] = useState(false), [selectedEdge, setSelectedEdge] = useState<string | null>(null), [selectedNode, setSelectedNode] = useState<string | null>(null), [statusOpen, setStatusOpen] = useState(false);
  const current = pipelines.find((p) => p.id === pipelineID);
  const editable = editing || (!readOnly && (!version || version.status === "draft"));
  const load = useCallback(async () => { try { if (readOnly) { const item = await request<Pipeline>(`review/pipelines/select${runtimeProfileID ? `?profile_id=${runtimeProfileID}` : ""}`); const active = item.versions.find((candidate) => candidate.status === "published"); setPipelines([item]); if (active) open(active, item); return; } const items = await request<Pipeline[]>("review/pipelines"); setPipelines(items); } catch (e) { if (e instanceof Error && e.message === "AUTH") onAuthError(); else setError(e instanceof Error ? e.message : String(e)); } }, [request, onAuthError, readOnly, runtimeProfileID, manualApproval]);
  useEffect(() => { void load(); }, [load]);
  const stageType = (key: string) => catalog.find((item) => item.key === key);
  const buildNode = useCallback((stage: Stage, index: number): Node<StudioNodeData> => { const fallback = defaultPositions[index] ?? { x: 160 + (index % 4) * 360, y: 160 + Math.floor(index / 4) * 290 }; return { id: stage.key, type: "studio", position: { x: Number(stage.config?.x ?? fallback.x), y: Number(stage.config?.y ?? fallback.y) }, data: { stage, editable, runtime: runtimeEvents[stage.key], active: activeStage === stage.key, select: () => { setSelectedNode(stage.key); setStatusOpen(false); }, openLogs: () => { if (stage.key === "pre-publicacao") onOpenPreReview?.(); else onOpenLogs?.(stage.key, stage.name, runtimeLogs[stage.key] || []); }, update: (patch) => setNodes((all) => all.map((n) => n.id === stage.key ? { ...n, data: { ...n.data, stage: { ...n.data.stage, ...patch } } } : n)), remove: () => { setNodes((all) => all.filter((n) => n.id !== stage.key)); setEdges((all) => all.filter((e) => e.source !== stage.key && e.target !== stage.key)); }, } }; }, [editable, runtimeEvents, runtimeLogs, activeStage, onOpenLogs, onOpenPreReview, setNodes, setEdges]);
  function open(versionToOpen: Version, parent: Pipeline) {
    setPipelineID(parent.id); setVersion(versionToOpen); setName(parent.name); onPipelineName?.(parent.name);
    setDescription(parent.description); setProfileID(String(versionToOpen.profile_id ?? parent.profile_id ?? ""));
    setTriggers(versionToOpen.triggers.length ? versionToOpen.triggers : triggers);
    const byID = new Map(versionToOpen.stages.map((stage) => [stage.id, stage.key]));
    const stages = [...versionToOpen.stages];
    if (readOnly && manualApproval) stages.splice(Math.max(0, stages.findIndex((stage) => stage.executor_key === "publication")), 0, { stage_type_key: "pre-publicacao", executor_key: "pre-publicacao", key: "pre-publicacao", name: "Pré-publicação", prompt_template: "", max_output_tokens: 0, retry_limit: 0, timeout_seconds: 0, use_llm: false, required: false, config: { x: 1200, y: 430, input_side: "right", output_side: "left" } });
    setNodes(stages.map(buildNode));
    const stageByKey = new Map(stages.map((stage) => [stage.key, stage]));
    const ports = (source: string, target: string) => ({ sourceHandle: `output-${portSide(stageByKey.get(source)!, "output")}`, targetHandle: `input-${portSide(stageByKey.get(target)!, "input")}` });
    const transitions = versionToOpen.transitions.filter((item) => item.from_stage_id && item.to_stage_id).map((item, index) => {
      const source = byID.get(item.from_stage_id!)!, target = byID.get(item.to_stage_id!)!;
      return { id: String(item.id ?? index), source, target, ...ports(source, target), label: `${item.type}:${item.condition_key}`, data: item, animated: item.type !== "success", style: { stroke: contractColor(stageByKey.get(source)?.output_contract?.key) } };
    });
    if (readOnly && manualApproval) {
      const formatting = stages.find((stage) => stage.executor_key === "formatting")?.key;
      const publication = stages.find((stage) => stage.executor_key === "publication")?.key;
      if (formatting && publication) {
        const index = transitions.findIndex((edge) => edge.source === formatting && edge.target === publication);
        if (index >= 0) transitions.splice(index, 1);
        transitions.push({ id: "formatting-pre-publicacao", source: formatting, target: "pre-publicacao", ...ports(formatting, "pre-publicacao"), label: "success:always", data: { type: "success", condition_key: "always", priority: 0 }, animated: false, style: { stroke: contractColor(stageByKey.get(formatting)?.output_contract?.key) } }, { id: "pre-publicacao-publication", source: "pre-publicacao", target: publication, ...ports("pre-publicacao", publication), label: "approval", data: { type: "success", condition_key: "always", priority: 0 }, animated: false, style: { stroke: "#e6a34e" } });
      }
    }
    setEdges(transitions);
  }
  function create() { setPipelineID(null); setVersion(null); setName(""); setDescription(""); setProfileID(""); const keys = ["preparation", "verification", "formatting", "publication"]; const stages = keys.map((key, index) => newStage(key, index)); setNodes(stages.map(buildNode)); setEdges(stages.slice(0, -1).map((s, i) => ({ id: `e-${i}`, source: s.key, target: stages[i + 1].key, label: "success:always", data: { type: "success", condition_key: "always", priority: 0 } }))); }
  function discard() { if (version && current) open(version, current); else create(); setError(""); }
  function newStage(typeKey: string, index = nodes.length): Stage { const type = stageType(typeKey); const fixed: Record<string, [string, string, boolean, boolean]> = { preparation: ["preparacao", "Preparação", false, true], verification: ["verificacao", "Verificação", true, true], formatting: ["formatacao", "Formatação", true, true], publication: ["publicacao", "Publicação", false, true], error_log: ["erro", "Log de erro", false, false] }; const [key, title, llm, required] = fixed[typeKey] ?? [`${typeKey}-${Date.now()}`, type?.name ?? typeKey, true, false]; return { stage_type_key: typeKey, executor_key: type?.executor_key, key, name: title, prompt_template: "", max_output_tokens: 2000, retry_limit: 1, timeout_seconds: 900, use_llm: llm, required, config: { x: 100 + index * 70, y: 120 + index * 40 }, input_contract: type?.input_contract ? { key: type.input_contract.key } : undefined, output_contract: type?.output_contract ? { key: type.output_contract.key } : undefined }; }
  const connect = useCallback((connection: Connection) => { const source = nodes.find((node) => node.id === connection.source)?.data.stage, target = nodes.find((node) => node.id === connection.target)?.data.stage; if (!source || !target) return; if (target.executor_key !== "error_log" && source.output_contract?.key !== target.input_contract?.key) return setError("As portas só conectam contratos compatíveis."); const type = target.executor_key === "error_log" ? "failure" : "success"; setEdges((all) => addEdge({ ...connection, sourceHandle: `output-${portSide(source, "output")}`, targetHandle: `input-${portSide(target, "input")}`, id: crypto.randomUUID(), label: `${type}:always`, style: { stroke: contractColor(source.output_contract?.key) }, data: { type, condition_key: "always", priority: 0 } }, all)); }, [nodes, setEdges]);
  async function save(publish = false) { const stages = nodes.map((node, index) => ({ ...node.data.stage, config: { ...node.data.stage.config, x: node.position.x, y: node.position.y }, position: index + 1 })); const transitions = edges.map((edge, priority) => ({ from_stage_key: edge.source, to_stage_key: edge.target, type: String(edge.data?.type ?? "success"), condition_key: String(edge.data?.condition_key ?? "always"), priority })); const body = { name, description, profile_id: profileID ? Number(profileID) : null, stages, transitions, triggers };
    setBusy(true); setError(""); try { if (!version) { const key = name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || `pipeline-${Date.now()}`; const created = await request<Pipeline>("review/pipelines", { method: "POST", body: JSON.stringify({ ...body, key }) }); const draft = created.versions[0]; await load(); open(draft, created); } else if (current) { await request(`review/pipelines/${current.id}/drafts/${version.id}`, { method: "PUT", body: JSON.stringify(body) }); if (publish) { await request(`review/pipelines/${current.id}/drafts/${version.id}/publish`, { method: "POST" }); setVersion(null); } await load(); } onSaved(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setBusy(false); } }
  const updateSelectedEdge = (patch: Record<string, unknown>) => setEdges((all) => all.map((edge) => edge.id === selectedEdge ? { ...edge, label: `${String(patch.type ?? edge.data?.type)}:${String(patch.condition_key ?? edge.data?.condition_key)}`, data: { ...edge.data, ...patch } } : edge));
  async function createFromCurrent() { if (!current || !version) return; setBusy(true); try { const stages = nodes.map((node, index) => ({ ...node.data.stage, config: { ...node.data.stage.config, x: node.position.x, y: node.position.y }, position: index + 1 })); const transitions = edges.map((edge, priority) => ({ from_stage_key: edge.source, to_stage_key: edge.target, type: String(edge.data?.type ?? "success"), condition_key: String(edge.data?.condition_key ?? "always"), priority })); const key = draftName.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || `pipeline-${Date.now()}`; const created = await request<Pipeline>("review/pipelines", { method: "POST", body: JSON.stringify({ key, name: draftName, description, profile_id: runtimeProfileID ?? null, stages, transitions, triggers }) }); const draft = created.versions[0]; setEditing(true); onEditingChange?.(true); await load(); open(draft, created); } catch (failure) { setError(failure instanceof Error ? failure.message : String(failure)); } finally { setBusy(false); setNameDialog(false); } }
  useEffect(() => { if (readOnly && editRequest && current && version && !editing) { setDraftName(`Cópia de ${current.name}`); setNameDialog(true); } }, [editRequest, readOnly, current, version, editing]);
  useEffect(() => { if (editing && saveRequest) void save(); }, [saveRequest]);
  useEffect(() => { if (editing && discardRequest) { setEditing(false); onEditingChange?.(false); void load(); } }, [discardRequest]);
  useEffect(() => { if (readOnly) setNodes((all) => all.map((node) => ({ ...node, data: { ...node.data, runtime: runtimeEvents[node.id], active: activeStage === node.id } }))); }, [readOnly, runtimeEvents, activeStage, setNodes]);
  useEffect(() => { if (readOnly) setEdges((all) => all.map((edge) => ({ ...edge, animated: edge.source === activeStage || edge.target === activeStage, className: "studio-runtime-edge" }))); }, [readOnly, activeStage, setEdges]);
  useEffect(() => { if (editable) setEdges((all) => all.map((edge) => { const source = nodes.find((node) => node.id === edge.source)?.data.stage; const target = nodes.find((node) => node.id === edge.target)?.data.stage; return source && target ? { ...edge, sourceHandle: `output-${portSide(source, "output")}`, targetHandle: `input-${portSide(target, "input")}`, style: { ...edge.style, stroke: contractColor(source.output_contract?.key) } } : edge; })); }, [editable, nodes, setEdges]);
  const selectedStage = nodes.find((node) => node.id === selectedNode)?.data.stage;
  return <section className={`pipeline-studio ${readOnly ? "runtime-studio" : ""}`}>{nameDialog && <div className="studio-dialog-backdrop"><section className="studio-name-dialog"><h2>Nome da nova pipeline</h2><p>A cópia será vinculada ao profile padrão e poderá ser selecionada manualmente depois.</p><input autoFocus value={draftName} onChange={(event) => setDraftName(event.target.value)} /><div><button className="secondary-button" onClick={() => setNameDialog(false)}>Cancelar</button><button className="primary-button" disabled={!draftName.trim() || busy} onClick={() => void createFromCurrent()}>Criar pipeline</button></div></section></div>}{!readOnly && <header className="studio-topbar"><div><span className="eyebrow">Pipeline Studio</span><h2>{name || "Novo workflow"}</h2></div><div><button className="secondary-button" disabled={busy} onClick={discard}><RotateCcw size={16} /> Descartar</button>{editable && <button className="secondary-button" disabled={busy} onClick={() => void save()}><Save size={16} /> Salvar</button>}{editable && version && <button className="primary-button" disabled={busy} onClick={() => void save(true)}><Send size={16} /> Publicar</button>}</div></header>}{error && <div className="banner error">{error}</div>}
    {menuOpen && <aside className="studio-sidebar"><button className="studio-close" onClick={() => setMenuOpen(false)} aria-label="Fechar menu"><X size={16} /></button><section><strong>Workflows</strong>{pipelines.map((p) => <button key={p.id} className={p.id === pipelineID ? "active" : ""} disabled={readOnly} onClick={() => { setPipelineID(p.id); setVersion(null); setNodes([]); setEdges([]); }}><GitBranch size={15} /> {p.name}{p.is_default && <Star size={13} />}</button>)}</section>{current && !version && <section><strong>Versões</strong>{current.versions.map((v) => <button key={v.id} disabled={readOnly} onClick={() => open(v, current)}>v{v.version} <small>{v.status}</small></button>)}{!current.is_default && <button onClick={() => void request(`review/pipelines/${current.id}/select`, { method: "POST" }).then(() => load())}><Star size={15} /> Selecionar</button>}</section>}<section><strong>Etapas</strong>{catalog.filter((t) => t.is_enabled).map((type) => <button key={type.key} disabled={!editable} draggable onDragStart={(e) => e.dataTransfer.setData("stage", type.key)} onClick={() => editable && setNodes((all) => [...all, buildNode(newStage(type.key, all.length), all.length)])}><Plus size={14} /> {type.name}</button>)}</section><section><strong>Gatilhos</strong>{triggers.map((trigger) => <label className="studio-trigger" key={trigger.source}><input disabled={!editable} type="checkbox" checked={trigger.enabled} onChange={(e) => setTriggers((all) => all.map((t) => t.source === trigger.source ? { ...t, enabled: e.target.checked } : t))} /><Webhook size={14} /> {triggerLabels[trigger.source]}</label>)}</section></aside>}
    <main className="studio-canvas" onDragOver={(e) => e.preventDefault()} onDrop={(e) => { const type = e.dataTransfer.getData("stage"); if (!type || !editable) return; const rect = e.currentTarget.getBoundingClientRect(); const stage = newStage(type); stage.config = { ...stage.config, x: e.clientX - rect.left, y: e.clientY - rect.top }; setNodes((all) => [...all, buildNode(stage, all.length)]); }}><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} onConnect={connect} onEdgeClick={(_, edge) => { setSelectedEdge(edge.id); setSelectedNode(null); setStatusOpen(false); }} fitView><Background gap={18} size={1} /><Controls /></ReactFlow><button className="studio-menu-toggle" onClick={() => setMenuOpen(true)} title="Abrir menu"><PanelLeftOpen size={17} /></button><div className="studio-hint"><MousePointer2 size={14} /> Arraste etapas, conecte portas e use o card de erro para caminhos failure/fallback.</div><button className={`studio-status ${error ? "error" : "ok"}`} onClick={() => { setStatusOpen((value) => !value); setSelectedNode(null); }} title="Status da pipeline"><CircleAlert size={16} /> {error ? "Atenção" : "Válida"}</button></main>
    {(selectedStage || statusOpen) && <aside className="studio-inspector"><button className="studio-close" onClick={() => { setSelectedNode(null); setSelectedEdge(null); setStatusOpen(false); }} aria-label="Fechar detalhes"><X size={16} /></button>{selectedStage ? <StageInspector stage={selectedStage} editable={editable} runtime={runtimeEvents[selectedStage.key]} onUpdate={(patch) => setNodes((all) => all.map((node) => node.id === selectedStage.key ? { ...node, data: { ...node.data, stage: { ...node.data.stage, ...patch } } } : node))} /> : <><strong>Status da pipeline</strong><div className="studio-error-note"><CircleAlert size={15} /> {error || "Pipeline carregada. Rotas failure e fallback só podem apontar para Log de erro."}</div></>}{selectedEdge && <section className="studio-edge"><strong>Conexão</strong><label>Tipo<select disabled={!editable} value={String(edges.find((e) => e.id === selectedEdge)?.data?.type ?? "success")} onChange={(e) => updateSelectedEdge({ type: e.target.value })}>{["success", "failure", "fallback", "skip"].map((v) => <option key={v}>{v}</option>)}</select></label><label>Condição<select disabled={!editable} value={String(edges.find((e) => e.id === selectedEdge)?.data?.condition_key ?? "always")} onChange={(e) => updateSelectedEdge({ condition_key: e.target.value })}>{conditions.map((v) => <option key={v}>{v}</option>)}</select></label></section>}</aside>}
  </section>;
}
