import type { Resource } from "../types";
export const resources: Resource[] = [
  {
    name: "Providers",
    singular: "Provider",
    path: "ai/providers",
    description: "Provedores de inteligência artificial disponíveis.",
    icon: "AI",
    group: "IA",
    seeded: true,
    canDefault: true,
    fields: [
      { key: "display_name", label: "Nome de exibição", required: true },
      { key: "base_url", label: "URL base" },
      {
        key: "auth_type",
        label: "Tipo de autenticação",
        required: true,
        options: [
          { value: "none", label: "Sem autenticação" },
          { value: "bearer", label: "Bearer token" },
        ],
      },
      {
        key: "is_enabled",
        label: "Provider habilitado",
        type: "boolean",
        default: true,
      },
    ],
  },
  {
    name: "Conexões",
    singular: "Conexão",
    path: "ai/connections",
    description: "Endpoints e credenciais referenciadas por ambiente.",
    icon: "CN",
    group: "IA",
    canDefault: true,
    canTest: true,
    fields: [
      {
        key: "provider_id",
        label: "Provider",
        type: "number",
        required: true,
        reference: { path: "ai/providers", labelKeys: ["display_name"] },
      },
      { key: "name", label: "Nome da conexão", required: true },
      {
        key: "base_url",
        label: "URL base",
        hint: "Ex.: http://host.docker.internal:11434",
      },
      {
        key: "api_key_env_name",
        label: "Variável da API key",
        hint: "Somente o nome, como OPENROUTER_API_KEY.",
      },
      {
        key: "http_referer",
        label: "URL da aplicação",
        hint: "OpenRouter: cabeçalho opcional HTTP-Referer.",
      },
      {
        key: "app_title",
        label: "Nome da aplicação",
        hint: "OpenRouter: cabeçalho opcional X-OpenRouter-Title.",
      },
      { key: "is_default", label: "Conexão padrão", type: "boolean" },
      {
        key: "is_enabled",
        label: "Conexão habilitada",
        type: "boolean",
        default: true,
      },
    ],
  },
  {
    name: "Modelos",
    singular: "Modelo",
    path: "ai/models",
    description: "Modelos disponíveis em cada conexão.",
    icon: "MD",
    group: "IA",
    canDefault: true,
    fields: [
      {
        key: "connection_id",
        label: "Conexão",
        type: "number",
        required: true,
        reference: { path: "ai/connections", labelKeys: ["name", "base_url"] },
      },
      { key: "provider_model_name", label: "Nome no provider", required: true },
      { key: "display_name", label: "Nome de exibição", required: true },
      { key: "context_window", label: "Janela de contexto", type: "number" },
      {
        key: "max_output_tokens",
        label: "Máx. tokens de saída",
        type: "number",
      },
      { key: "supports_json", label: "Suporta JSON", type: "boolean" },
      { key: "supports_tools", label: "Suporta tools", type: "boolean" },
      {
        key: "supports_streaming",
        label: "Suporta streaming",
        type: "boolean",
      },
      { key: "is_default", label: "Modelo padrão", type: "boolean" },
      {
        key: "is_enabled",
        label: "Modelo habilitado",
        type: "boolean",
        default: true,
      },
    ],
  },
  {
    name: "Parâmetros",
    singular: "Parâmetro de modelo",
    path: "ai/model-parameters",
    description: "Ajustes de geração e ciclo de vida por modelo.",
    icon: "ƒ",
    group: "IA",
    fields: [
      {
        key: "model_id",
        label: "Modelo específico",
        type: "number",
        hint: "Opcional. Sem modelo específico, usa o provider padrão e o modelo padrão da conexão.",
        reference: {
          path: "ai/models",
          labelKeys: ["display_name", "provider_model_name"],
        },
      },
      { key: "temperature", label: "Temperature", type: "number" },
      { key: "top_p", label: "Top P", type: "number" },
      { key: "repeat_penalty", label: "Repeat penalty", type: "number" },
      { key: "num_ctx", label: "Num ctx", type: "number" },
      { key: "num_threads", label: "Threads", type: "number" },
      { key: "num_predict", label: "Num predict", type: "number" },
      {
        key: "keep_alive",
        label: "Keep alive",
        hint: "Ex.: 5m. Aplicável ao Ollama.",
      },
      {
        key: "timeout_seconds",
        label: "Timeout (segundos)",
        type: "number",
        default: 900,
      },
      {
        key: "unload_model_after_review",
        label: "Descarregar após o review",
        type: "boolean",
      },
    ],
  },
  {
    name: "Profiles",
    singular: "Profile",
    path: "review/profiles",
    description: "Agrupam modelo e política de revisão.",
    icon: "PF",
    group: "Review",
    canDefault: true,
    fields: [
      { key: "name", label: "Nome", required: true },
      { key: "description", label: "Descrição" },
      {
        key: "model_id",
        label: "Modelo",
        type: "number",
        required: true,
        reference: {
          path: "ai/models",
          labelKeys: ["display_name", "provider_model_name"],
        },
      },
      { key: "is_default", label: "Profile padrão", type: "boolean" },
      {
        key: "is_enabled",
        label: "Profile habilitado",
        type: "boolean",
        default: true,
      },
    ],
  },
  {
    name: "Policies",
    singular: "Policy",
    path: "review/policies",
    description: "Limites, privacidade e comportamento do review.",
    icon: "PL",
    group: "Review",
    fields: [
      {
        key: "profile_id",
        label: "Profile",
        type: "number",
        required: true,
        reference: {
          path: "review/profiles",
          labelKeys: ["name", "description"],
        },
      },
      {
        key: "max_block_chars",
        label: "Máx. caracteres por bloco",
        type: "number",
        required: true,
      },
      {
        key: "max_files_per_block",
        label: "Máx. arquivos por bloco",
        type: "number",
        required: true,
      },
      {
        key: "review_concurrency",
        label: "Concorrência",
        type: "number",
        default: 1,
      },
      {
        key: "review_final_retries",
        label: "Tentativas da resposta final",
        type: "number",
        default: 5,
      },
      {
        key: "review_wip_pull_requests",
        label: "Revisar PRs WIP",
        type: "boolean",
      },
      {
        key: "review_own_pull_requests",
        label: "Revisar PR próprio",
        type: "boolean",
      },
      {
        key: "publish_manual_reviews",
        label: "Publicar reviews manuais",
        type: "boolean",
      },
      {
        key: "allow_autonomous_rejection",
        label: "Permitir decisão autônoma",
        type: "boolean",
      },
      {
        key: "log_sensitive_data",
        label: "Registrar dados sensíveis",
        type: "boolean",
      },
      {
        key: "unload_model_after_review",
        label: "Descarregar modelo",
        type: "boolean",
      },
    ],
  },
  {
    name: "Repositórios",
    singular: "Repositório",
    path: "repositories",
    description: "Profiles específicos por owner/repositório.",
    icon: "RP",
    group: "Integrações",
    fields: [
      {
        key: "gitea_instance_id",
        label: "Instância Gitea",
        type: "number",
        reference: {
          path: "gitea/instances",
          labelKeys: ["name", "base_url"],
          placeholder: "Usar instância padrão",
        },
      },
      { key: "owner", label: "Owner", required: true },
      { key: "name", label: "Nome", required: true },
      {
        key: "full_name",
        label: "Nome completo",
        required: true,
        hint: "Formato owner/repositório.",
      },
      {
        key: "review_profile_id",
        label: "Profile de revisão",
        type: "number",
        required: true,
        reference: {
          path: "review/profiles",
          labelKeys: ["name", "description"],
        },
      },
      {
        key: "is_enabled",
        label: "Review habilitado",
        type: "boolean",
        default: true,
      },
    ],
  },
  {
    name: "Gitea",
    singular: "Instância Gitea",
    path: "gitea/instances",
    description: "Instâncias Gitea conhecidas pelo ForgeReview.",
    icon: "GT",
    group: "Integrações",
    canDefault: true,
    fields: [
      { key: "name", label: "Nome", required: true },
      { key: "base_url", label: "URL base", required: true },
      { key: "bot_username", label: "Usuário do bot" },
      {
        key: "token_env_name",
        label: "Variável do token",
        hint: "Somente o nome da variável.",
      },
      { key: "is_default", label: "Instância padrão", type: "boolean" },
      {
        key: "is_enabled",
        label: "Instância habilitada",
        type: "boolean",
        default: true,
      },
    ],
  },
];
export const navGroups = ["IA", "Review", "Integrações"] as const;
