"use client";
import { Activity, Plus, RefreshCw, ShieldCheck, Users } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { createUser, getAuditLog, getUsers, updateUser, type AuditEntry, type ManagedUser } from "../../lib/api";
import { useCurrentUser } from "../auth/AuthGate";
import { AppShell } from "../shell/AppShell";
import styles from "./AdminWorkspace.module.scss";

export function AdminWorkspace() {
  const current = useCurrentUser(); const [users, setUsers] = useState<ManagedUser[]>([]); const [audit, setAudit] = useState<AuditEntry[]>([]); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const load = async () => { setLoading(true); try { const [u, a] = await Promise.all([getUsers(), getAuditLog()]); setUsers(u); setAudit(a); } catch { setMessage("Não foi possível carregar a administração."); } finally { setLoading(false); } };
  useEffect(() => { if (current?.role === "admin") void load(); }, [current?.role]);
  if (current?.role !== "admin") return <AppShell title="Administração"><section className={styles.empty}><ShieldCheck /><h2>Acesso restrito</h2><p>Esta área exige papel de administrador.</p></section></AppShell>;
  const change = async (user: ManagedUser, role = user.role, active = user.active) => { setBusy(true); try { await updateUser(user.id, role, active); setMessage("Permissões atualizadas e sessões afetadas foram revogadas."); await load(); } catch { setMessage("A alteração foi recusada para preservar o acesso administrativo."); } finally { setBusy(false); } };
  const create = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); setBusy(true); try { await createUser(String(data.get("email")), String(data.get("password")), String(data.get("role")) as ManagedUser["role"]); event.currentTarget.reset(); setMessage("Usuário criado. A conta poderá entrar no ambiente local."); await load(); } catch { setMessage("Não foi possível criar o usuário. Confira os requisitos informados."); } finally { setBusy(false); } };
  return <AppShell title="Administração" eyebrow="CONTROLES OPERACIONAIS" actions={<button className={styles.refresh} onClick={() => void load()} disabled={loading || busy}><RefreshCw size={15} /> Atualizar</button>}>
    <div className={styles.summary}><article><Users /><div><span>CONTAS GERENCIADAS</span><strong>{loading ? "—" : users.length}</strong></div></article><article><ShieldCheck /><div><span>ADMINISTRADORES ATIVOS</span><strong>{loading ? "—" : users.filter((user) => user.role === "admin" && user.active).length}</strong></div></article><article><Activity /><div><span>EVENTOS VISÍVEIS</span><strong>{loading ? "—" : audit.length}</strong></div></article></div>
    {message && <p className={styles.feedback} role="status">{message}</p>}
    <div className={styles.grid}><section className={styles.panel}><div className={styles.panelHeading}><div><p>ACESSO</p><h2>Usuários</h2></div></div>
      <form className={styles.create} onSubmit={create}><label>E-mail<input required name="email" type="email" autoComplete="email" placeholder="nome@empresa.com" /></label><label>Senha inicial<input required name="password" type="password" minLength={12} autoComplete="new-password" placeholder="12 ou mais caracteres" /></label><label>Papel<select name="role" defaultValue="viewer"><option value="viewer">Visualizador</option><option value="editor">Editor</option><option value="admin">Administrador</option></select></label><button disabled={busy}><Plus size={15} /> Criar usuário</button></form>
      {loading ? <p className={styles.state} role="status">Carregando contas…</p> : users.length === 0 ? <Empty text="Nenhuma conta disponível para exibir." /> : <div className={styles.tableWrap}><table><caption className="srOnly">Contas locais</caption><thead><tr><th>Conta</th><th>Papel</th><th>Status</th><th>Ação</th></tr></thead><tbody>{users.map((user) => <tr key={user.id}><td><strong>{user.email}</strong>{user.id === current.id && <small>Você</small>}</td><td><select aria-label={`Papel de ${user.email}`} value={user.role} disabled={busy || user.id === current.id} onChange={(event) => void change(user, event.target.value as ManagedUser["role"])}><option value="viewer">Visualizador</option><option value="editor">Editor</option><option value="admin">Administrador</option></select></td><td><span className={user.active ? styles.active : styles.inactive}>{user.active ? "Ativa" : "Inativa"}</span></td><td><button className={styles.secondary} disabled={busy || user.id === current.id} onClick={() => void change(user, user.role, !user.active)}>{user.active ? "Desativar" : "Ativar"}</button></td></tr>)}</tbody></table></div>}</section>
      <section className={styles.panel}><div className={styles.panelHeading}><div><p>RECONCILIAÇÃO</p><h2>Trilha de auditoria</h2></div></div>{loading ? <p className={styles.state} role="status">Carregando eventos…</p> : audit.length === 0 ? <Empty text="Ainda não há eventos administrativos registrados." /> : <ol className={styles.audit}>{audit.map((item) => <li key={item.id}><span></span><div><strong>{item.action}</strong><p>{item.target}</p><time dateTime={item.created_at}>{formatDate(item.created_at)}</time></div></li>)}</ol>}</section></div>
  </AppShell>;
}
function Empty({ text }: { text: string }) { return <div className={styles.empty}><ShieldCheck /><p>{text}</p></div>; }
function formatDate(value: string) { const date = new Date(value.replace(" ", "T") + (value.endsWith("Z") ? "" : "Z")); return Number.isNaN(date.valueOf()) ? "Data indisponível" : new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(date); }
